# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8e0f5d5008ba46665317131b5e0db1e4f5b8e97d00a685b988f015508592af48b7eeb235c92b05b9ba2c8084e644bff346daba718f976d463725fa3fd3dce1d

test:
  secret_key_base: 26374197fa6cfb0a84bc315331221c6e543d317b71780545ae51d788de9c92e25928e7d55de90af5ca50bd997e56ef4601cf0c80c3d7478c491df25127404d63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
